name: Trigger-DevOps-Build
on: 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'YOUR_GITHUB_USERNAME_OR_ORGANIZATION_NAME'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Trigger Production
      run: |
        export AZURE_DEVOPS_EXT_PAT=${{ secrets.AZURE_DEVOPS_TOKEN }}
        chmod +x .workflow/build-production.sh
        bash ./.workflow/build-production.sh
